In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import sentence_transformers

from google import genai

In [3]:
df=pd.read_csv("scraped_1.csv")

In [4]:
df.head()

Competition Name  \
0  ASME-DTU Research and Development Department's...   
1                     Call For Articles: Finmagazine   
2                     Data Analytics Quiz by SME-DTU   
3  Nayan: The Annual Short Filmmaking Competition...   
4  Data & Beyond: A Data Analytics Competition by...   

                                     Competition URL  \
0  https://unstop.com/quiz/asme-dtu-research-and-...   
1  https://unstop.com/competitions/call-for-artic...   
2  https://unstop.com/quiz/data-analytics-quiz-de...   
3  https://unstop.com/events/nayan-dtu-new-delhi-...   
4  https://unstop.com/competitions/data-beyond-a-...   

                                         Organizer   Status      Event Type  \
0  Delhi Technological University (DTU), New Delhi  Expired            Quiz   
1  Delhi Technological University (DTU), New Delhi  Expired     Competition   
2  Delhi Technological University (DTU), New Delhi  Expired            Quiz   
3  Delhi Technological University (DTU), New Delhi  Expired  Cultural Event   
4  Delhi Technological University (DTU), New Delhi  Expired     Competition   

  Posted Date  Impressions                                              tags  
0  09/11/2025       7524.0                    Online Quiz Everyone can apply  
1  10/11/2025      36006.0                Everyone can apply Article Writing  
2  01/18/2022     128000.0          Business Engineering Others Data Science  
3  02/06/2025      12785.0  Everyone can apply Dramatics Writing Photography  
4  10/23/2021      34968.0        Engineering Business Others Data Analytics

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555 entries, 0 to 554
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Competition Name  555 non-null    object 
 1   Competition URL   555 non-null    object 
 2   Organizer         555 non-null    object 
 3   Status            555 non-null    object 
 4   Event Type        555 non-null    object 
 5   Posted Date       553 non-null    object 
 6   Impressions       548 non-null    float64
 7   tags              553 non-null    object 
dtypes: float64(1), object(7)
memory usage: 34.8+ KB


In [6]:
df.describe()

Impressions
count  5.480000e+02
mean   2.044166e+05
std    3.129871e+06
min    2.000000e+00
25%    1.021675e+04
50%    1.844400e+04
75%    3.227075e+04
max    6.851000e+07

In [10]:
df['tags'].unique()

array(['Online Quiz Everyone can apply',
       'Everyone can apply Article Writing',
       'Business Engineering Others Data Science',
       'Everyone can apply Dramatics Writing Photography',
       'Engineering Business Others Data Analytics',
       'Case Study Strategy Everyone can apply',
       'Engineering Others Data Science Workshops',
       'Others Sports College Festival On Campus Quiz',
       'Conference Everyone can apply', 'Workshops Everyone can apply',
       'Dramatics Undergraduate Postgraduate Engineering Students', nan,
       'Business Plan Everyone can apply',
       'Online Quiz Undergraduate Postgraduate Engineering Students',
       'Coding Challenge Hackathon Undergraduate Engineering Students',
       'Case Study Business Plan College Festival Undergraduate',
       'Undergraduate Postgraduate Engineering Students Coding Challenge',
       'Business Plan Postgraduate',
       'Hackathon Robotics Presentation Undergraduate',
       'Engineering Students M

In [24]:
from keybert import KeyBERT
kw=KeyBERT()

In [90]:
df['Impressions'].mean()

204416.6295620438

In [70]:
null_data=df2[df2['Impressions'].isnull()]
null_data


Competition Name  \
19                                  60-Second Symphony   
20                                Pixel Fusion Odyssey   
21                                        AI Cinemagic   
26                                        Sound & Fury   
31                           Astrophotography Workshop   
47                 Sales Executive – Campus Ambassador   
170  Paytm Event: "Best PTE Coaching in Hyderabad –...   

                                       Competition URL  \
19   https://unstop.com/events/60-second-symphony-v...   
20   https://unstop.com/events/pixel-fusion-odyssey...   
21   https://unstop.com/events/ai-cinemagic-visions...   
26   https://unstop.com/events/sound-fury-visions25...   
31   https://unstop.com/workshops-webinars/astropho...   
47   https://unstop.com/jobs/sales-executive-campus...   
170  https://unstop.com/workshops-webinars/paytm-ev...   

                                           Organizer   Status      Event Type  \
19   Delhi Technological University (DTU), New Delhi  Expired  Cultural Event   
20   Delhi Technological University (DTU), New Delhi  Expired  Cultural Event   
21   Delhi Technological University (DTU), New Delhi  Expired  Cultural Event   
26   Delhi Technological University (DTU), New Delhi  Expired  Cultural Event   
31   Delhi Technological University (DTU), New Delhi  Expired        Workshop   
47                                  Knowledge Center     Live     Competition   
170  Delhi Technological University (DTU), New Delhi  Expired        Workshop   

    Posted Date  Impressions  \
19   08/26/2025          NaN   
20   08/25/2025          NaN   
21   08/26/2025          NaN   
26   08/26/2025          NaN   
31   09/08/2025          NaN   
47   11/06/2025          NaN   
170  12/18/2024          NaN   

                                                  tags  
19   Engineering Students MBA Students Undergraduat...  
20   Engineering Students MBA Students Undergraduat...  
21   Engineering Students MBA Students Undergraduat...  
26   Engineering Students MBA Students Undergraduat...  
31   Workshops Photography College Festival On Camp...  
47                           Experienced Professionals  
170                       Workshops Everyone can apply

In [ ]:
#trying to groupby event type and then performing imputation

In [83]:
df2['Impressions'] = df2.groupby('Event Type').Impressions.transform(lambda x: x.fillna(x.mean()))


C:\Users\Shreyansh\AppData\Local\Temp\ipykernel_29456\3083183435.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Impressions'] = df2.groupby('Event Type').Impressions.transform(lambda x: x.fillna(x.mean()))


In [108]:
data=[]
for i in range(0,len(df)):
    name=df.loc[i]['Competition Name']
    data.append(name)
data

["ASME-DTU Research and Development Department's Recruitment Test",
 'Call For Articles: Finmagazine',
 'Data Analytics Quiz by SME-DTU',
 'Nayan: The Annual Short Filmmaking Competition of DTU',
 'Data & Beyond: A Data Analytics Competition by SME-DTU',
 "L'Oréal Brandstorm 2026",
 'Kickstart to Machine Learning by Round Table DTU and #Define BPIT',
 'Panenka 2.0',
 'Sahaj: Understanding Stress & Finding Balance',
 'TechWeek 2K25',
 'Chitrakatha – Intercollege Reel Making Competition',
 'Unstop Career League 2025',
 'Dream To Deal',
 "Cogniwars'25",
 'Hackathon on Lightweight and Resource-Efficient HPC and AI models for Social Welfare',
 'Dream Forge 2.0',
 'Speedathon',
 'Reliance T.U.P XI',
 'Tinkercase',
 '60-Second Symphony',
 'Pixel Fusion Odyssey',
 'AI Cinemagic',
 'ASTRA 2025 Hackathon – Where Curiosity Meets Cosmic',
 'Unstop Tech Fair 2025',
 'CineBlitz- 24 Hours Video Editing Hackathon',
 'Trailer Remix Challenge',
 'Sound & Fury',
 'Still Stories',
 'Cinewalk Exploration',

In [125]:
df2=df2[df2['Organizer']=="Delhi Technological University (DTU), New Delhi"]

    

In [140]:
df=df2
df=df.reset_index()


In [148]:
tag_new=[]
for i in range(0,len(df)):
    tag=df.loc[i]['Competition Name']
    tag_new.append(kw.extract_keywords(tag,keyphrase_ngram_range=(1,2),stop_words=None))

In [149]:
tag_new

[[('recruitment test', 0.7209),
  ('department recruitment', 0.6733),
  ('asme dtu', 0.6312),
  ('recruitment', 0.6169),
  ('dtu research', 0.5987)],
 [('articles finmagazine', 0.9479),
  ('finmagazine', 0.7828),
  ('articles', 0.5585),
  ('for articles', 0.5088),
  ('call for', 0.205)],
 [('analytics quiz', 0.685),
  ('sme dtu', 0.6527),
  ('dtu', 0.5664),
  ('data analytics', 0.5502),
  ('analytics', 0.5403)],
 [('short filmmaking', 0.7233),
  ('filmmaking competition', 0.69),
  ('filmmaking', 0.648),
  ('of dtu', 0.4817),
  ('dtu', 0.4756)],
 [('analytics competition', 0.6024),
  ('sme dtu', 0.5839),
  ('data analytics', 0.5458),
  ('data beyond', 0.5077),
  ('analytics', 0.504)],
 [('panenka', 0.7711)],
 [('understanding stress', 0.6657),
  ('stress finding', 0.6488),
  ('stress', 0.5986),
  ('sahaj understanding', 0.5897),
  ('balance', 0.5318)],
 [('techweek 2k25', 1.0), ('techweek', 0.799), ('2k25', 0.6211)],
 [('chitrakatha intercollege', 0.638),
  ('intercollege reel', 0.63),


In [ ]:
#f\adding newly computed tags to a list: may use it later for stength score
to_cal=[]
for i in range(0,len(df)):
    to_cal.append(tag_new[i][0][0])

In [164]:
df=df.drop(columns=['index'])

In [160]:
from sentence_transformers import SentenceTransformer

In [161]:
model=SentenceTransformer("all-MiniLM-L6-v2")

In [276]:
df['Impressions']=df['Impressions'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Competition Name  453 non-null    object
 1   Competition URL   453 non-null    object
 2   Organizer         453 non-null    object
 3   Status            453 non-null    object
 4   Event Type        453 non-null    object
 5   Posted Date       453 non-null    object
 6   Impressions       453 non-null    object
 7   tags              453 non-null    object
 8   decription        453 non-null    object
dtypes: object(9)
memory usage: 32.0+ KB


In [320]:
#comparing only using tags
to_compare=df['tags']

In [321]:
to_compare_embedding=model.encode(to_compare)

In [322]:
query="i am interested in Workshops"
query_embeddings=model.encode(query)

In [323]:
similarity_score=model.similarity(to_compare_embedding,query_embeddings)


In [324]:
import torch
val,ind=torch.topk(similarity_score,dim=0,k=3)

In [325]:
ind

tensor([[256],
        [  7],
        [143]])

In [326]:
df.loc[256]

Competition Name                                     Trading Bootcamp
Competition URL     https://unstop.com/workshops-webinars/groww-pl...
Organizer             Delhi Technological University (DTU), New Delhi
Status                                                        Expired
Event Type                                                   Workshop
Posted Date                                                04/20/2023
Impressions                                                    8677.0
tags                                     Workshops Everyone can apply
decription          Trading Bootcampdo attend if interested inWork...
Name: 256, dtype: object

In [327]:
#trying approach 2, adding up columns to compute the similarity


In [328]:
df['decription']=df['Competition Name']+"do attend if interested in"+df["tags"]+"it is a"+df["Event Type"]+"event"+"with "+df['Impressions']+"number of impressions"

In [329]:
to_compare_desc=df['decription']
to_compare_desc_embeddings=model.encode(to_compare_desc)
similarity_score_2=model.similarity(to_compare_desc_embeddings,query_embeddings)

In [330]:
val,ind2=torch.topk(similarity_score_2,dim=0,k=3)
ind2

tensor([[383],
        [385],
        [ 72]])

In [331]:
df.loc[383]

Competition Name    Art Workshop- Charcoal Shading Workshop and Hu...
Competition URL     https://unstop.com/workshops-webinars/art-work...
Organizer             Delhi Technological University (DTU), New Delhi
Status                                                        Expired
Event Type                                                   Workshop
Posted Date                                                08/07/2021
Impressions                                                    9367.0
tags                    Others Designing Workshops Everyone can apply
decription          Art Workshop- Charcoal Shading Workshop and Hu...
Name: 383, dtype: object

In [303]:
#resource exhausted
interests=["ai,ml,business"]
interest = client.models.embed_content(
        model="gemini-embedding-001",
        contents=interests
)

desc=client.models.embed_content(
    model="gemini-embedding-001",
    contents=to_compare_desc[:100].to_list()
)



ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/embed_content_free_tier_requests, limit: 0', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/embed_content_free_tier_requests', 'quotaId': 'EmbedContentRequestsPerMinutePerUserPerProjectPerModel-FreeTier'}]}]}}

In [332]:
#moving on to interest based recommendation
interests="ai ml business"
interest_embeddings=model.encode(interests)
sim_score=model.similarity(interest_embeddings,to_compare_desc_embeddings)

val3,ind3=torch.topk(sim_score,dim=1,k=1)
ind3

tensor([[189]])

In [333]:
df.loc[150]

Competition Name                                   Cryptic Hunt on ML
Competition URL     https://unstop.com/hackathons/cryptic-hunt-on-...
Organizer             Delhi Technological University (DTU), New Delhi
Status                                                        Expired
Event Type                                                  Hackathon
Posted Date                                                08/10/2024
Impressions                                                   67879.0
tags                Engineering Students MBA Students Undergraduat...
decription          Cryptic Hunt on MLdo attend if interested inEn...
Name: 150, dtype: object

In [334]:
#attended based history
attended_Events=["Applications of Aritifical intelligence in finance","workshop on Machine learning"]
attended=""
for i in attended_Events:
    attended+=i
attended_events_embeddings=model.encode(attended)


In [335]:
similarity_score_3=model.similarity(attended_events_embeddings,to_compare_desc_embeddings)
val4,ind4=torch.topk(similarity_score_3,dim=1,k=3)
ind4

tensor([[314,  64, 377]])

In [336]:
df.loc[314]

Competition Name                Introduction to Stock Market Analysis
Competition URL     https://unstop.com/workshops-webinars/introduc...
Organizer             Delhi Technological University (DTU), New Delhi
Status                                                        Expired
Event Type                                                   Workshop
Posted Date                                                08/10/2021
Impressions                                                    3813.0
tags                 Business Engineering Data Science Data Analytics
decription          Introduction to Stock Market Analysisdo attend...
Name: 314, dtype: object